package com.hibernate.entity;
// Generated 2015-9-29 14:22:55 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Calendar;

/**
 * Sensor generated by hbm2java
 */

public class Sensor implements Serializable{

	/** 
	* @Fields serialVersionUID : TODO(用一句话描述这个变量表示什么) 
	*/ 
	private static final long serialVersionUID = -4608316325717990173L;
	private String id;
	private String dtuId;
	private LMU lmu;
	private String dtuName;
	private BigDecimal v0; //未用
	private BigDecimal v1;//氨气
	private BigDecimal v2;//温度
	private BigDecimal v3;//湿度
	private BigDecimal v4;//一路
	private BigDecimal v5;//二路
	private BigDecimal v6;//三路
	private BigDecimal v7;//四路
	private BigDecimal v8;//五路
	private BigDecimal v9;//六路
	private BigDecimal v10;//七路
	private BigDecimal v11;//八路

	public BigDecimal getV11() {
		return v11;
	}

	public void setV11(BigDecimal v11) {
		this.v11 = v11;
	}

	public BigDecimal getV10() {
		return v10;
	}

	public void setV10(BigDecimal v10) {
		this.v10 = v10;
	}

	private Calendar addtime;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public LMU getLmu() {
		return this.lmu;
	}

	public void setLmu(LMU lmu) {
		this.lmu = lmu;
	}

	public BigDecimal getV0() {
		return this.v0;
	}

	public void setV0(BigDecimal v0) {
		this.v0 = v0;
	}

	public BigDecimal getV1() {
		return this.v1;
	}

	public void setV1(BigDecimal v1) {
		this.v1 = v1;
	}

	public BigDecimal getV2() {
		return this.v2;
	}

	public void setV2(BigDecimal v2) {
		this.v2 = v2;
	}

	public BigDecimal getV3() {
		return this.v3;
	}

	public void setV3(BigDecimal v3) {
		this.v3 = v3;
	}

	public BigDecimal getV4() {
		return this.v4;
	}

	public void setV4(BigDecimal v4) {
		this.v4 = v4;
	}

	public BigDecimal getV5() {
		return this.v5;
	}

	public void setV5(BigDecimal v5) {
		this.v5 = v5;
	}

	public BigDecimal getV6() {
		return this.v6;
	}

	public void setV6(BigDecimal v6) {
		this.v6 = v6;
	}

	public BigDecimal getV7() {
		return this.v7;
	}

	public void setV7(BigDecimal v7) {
		this.v7 = v7;
	}

	public BigDecimal getV8() {
		return this.v8;
	}

	public void setV8(BigDecimal v8) {
		this.v8 = v8;
	}

	public BigDecimal getV9() {
		return this.v9;
	}

	public void setV9(BigDecimal v9) {
		this.v9 = v9;
	}

	public Calendar getAddtime() {
		return addtime;
	}

	public void setAddtime(Calendar addtime) {
		this.addtime = addtime;
	}

	public String getDtuId() {
		return dtuId;
	}

	public void setDtuId(String dtuId) {
		this.dtuId = dtuId;
	}

	public String getDtuName() {
		return dtuName;
	}

	public void setDtuName(String dtuName) {
		this.dtuName = dtuName;
	}

}
